### ISSUE TITLE
Grafana's AutoTracing failed to obtain data

### ISSUE THREAD

**Issue by liyk1024** [deepflowys/deepflow#1237]
# Expected Behavior
Grafana's AutoTracing View Distributed Tracing

# Actual Behavior
Grafana's AutoTracing failed to obtain data

# Steps to Reproduce the Problem
1. Reference document deployment, https://deepflow.yunshan.net/docs/zh/install/single-k8s/
2. Unable to display data when accessing grafana Distributed Tracing
3. ERROR：  Unknown tag: endpoint; status:500 statusText:"Internal Server Error"
 
# Additional Info

-  deepflow version:
   **Output of `kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v`:**

   **Output of `kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`:**

```
Name: deepflow-server community edition
Branch: 
CommitID: 71548431bc2779fd4b3be2e75c4eebab9061abb6
RevCount: 6683
Compiler: go version go1.18.6 linux/amd64
CompileTime: 2022-10-13 11:45:30 


Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
6683-71548431bc2779fd4b3be2e75c4eebab9061abb6
Name: deepflow-agent community edition
Branch: HEAD
CommitId: 71548431bc2779fd4b3be2e75c4eebab9061abb6
RevCount: 6683
Compiler: rustc 1.64.0 (a55dd71d5 2022-09-19)
CompileTime: 2022-10-13 03:46:18
```

- deepflow agent list:

  **Output of `deepflow-ctl agent list`:**
```
NAME     TYPE       CTRL_IP          CTRL_MAC           STATE    EXCEPTIONS GROUP
node1-V3 K8S_VM     192.168.1.4      52:54:f6:44:b1:ae  RUNNING  2          default
node2-V1 K8S_VM     192.168.1.5      52:54:f6:0d:d5:04  RUNNING             default
```

- Kubernetes CNI:

```
[root@master ~]# calicoctl version
Client Version:    v3.21.5
Git commit:        1b5d26bcb
Cluster Version:   v3.21.5
Cluster Type:      kubespray,kubeadm,kdd,k8s
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  
  **Output of `uname -r`:**
```
CentOS Linux 7 (Core)
3.10.0-1127.el7.x86_64
```

{"OPT_STATUS":"FAIL","DESCRIPTION":"code: 62, message: Syntax error: failed at position 2 ('FROM'): FROM flow_log.`l7_flow_log` PREWHERE `time` \u003e= 1666849617 AND `time` \u003c= 1666851417 LIMIT 100. Expected one of: ALTER query, Query with output, ALTER PROFILE, RENAME DATABASE, SHOW PRIVILEGES query, TRUNCATE, KILL, KILL QUERY query, SELECT query, possibly with UNION, list of union elements, ALTER ROLE, SELECT subquery, DESCRIBE query, SELECT query, subquery, possibly with UNION, SHOW GRANTS, SHOW CREATE, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, WATCH, SHOW PROCESSLIST query, ALTER POLICY, ALTER USER, CREATE VIEW query, CHECK TABLE, SET ROLE, SELECT query, SELECT, REVOKE, CREATE USER, CREATE DICTIONARY, CREATE PROFILE, SET ROLE DEFAULT, ALTER SETTINGS PROFILE, EXPLAIN, SYSTEM, ALTER LIVE VIEW, RENAME TABLE, DROP query, SHOW ACCESS, OPTIMIZE query, USE, DROP access entity query, RENAME DICTIONARY, DETACH, SET, SHOW, DESC, OPTIMIZE TABLE, CREATE ROW POLICY, SET DEFAULT ROLE, EXCHANGE DICTIONARIES, CREATE POLICY, ALTER ROW POLICY, INSERT INTO, INSERT query, SHOW [TEMPORARY] TABLES|DATABASES|CLUSTERS|CLUSTER 'name' [[NOT] [I]LIKE 'str'] [LIMIT expr], GRANT, RENAME query, SHOW GRANTS query, SHOW PRIVILEGES, EXISTS, DROP, SYSTEM query, CREATE LIVE VIEW query, CREATE ROW POLICY or ALTER ROW POLICY query, CREATE QUOTA or ALTER QUOTA query, SHOW PROCESSLIST, ALTER QUOTA, CREATE QUOTA, CREATE DATABASE query, SET query, Query, CREATE, WITH, CREATE ROLE or ALTER ROLE query, EXTERNAL DDL FROM, EXCHANGE TABLES, EXISTS or SHOW CREATE query, WATCH query, REPLACE, CREATE ROLE, CREATE SETTINGS PROFILE, SET ROLE or SET DEFAULT ROLE query, CREATE USER or ALTER USER query, EXTERNAL DDL query, SHOW ACCESS query, SHOW CREATE QUOTA query, USE query, ATTACH, DESCRIBE, ALTER TABLE, ShowAccessEntitiesQuery, GRANT or REVOKE query, CREATE TABLE or ATTACH TABLE query","result":null,"debug":{"error":"code: 62, message: Syntax error: failed at position 2 ('FROM'): FROM flow_log.`l7_flow_log` PREWHERE `time` \u003e= 1666849617 AND `time` \u003c= 1666851417 LIMIT 100. Expected one of: ALTER query, Query with output, ALTER PROFILE, RENAME DATABASE, SHOW PRIVILEGES query, TRUNCATE, KILL, KILL QUERY query, SELECT query, possibly with UNION, list of union elements, ALTER ROLE, SELECT subquery, DESCRIBE query, SELECT query, subquery, possibly with UNION, SHOW GRANTS, SHOW CREATE, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, WATCH, SHOW PROCESSLIST query, ALTER POLICY, ALTER USER, CREATE VIEW query, CHECK TABLE, SET ROLE, SELECT query, SELECT, REVOKE, CREATE USER, CREATE DICTIONARY, CREATE PROFILE, SET ROLE DEFAULT, ALTER SETTINGS PROFILE, EXPLAIN, SYSTEM, ALTER LIVE VIEW, RENAME TABLE, DROP query, SHOW ACCESS, OPTIMIZE query, USE, DROP access entity query, RENAME DICTIONARY, DETACH, SET, SHOW, DESC, OPTIMIZE TABLE, CREATE ROW POLICY, SET DEFAULT ROLE, EXCHANGE DICTIONARIES, CREATE POLICY, ALTER ROW POLICY, INSERT INTO, INSERT query, SHOW [TEMPORARY] TABLES|DATABASES|CLUSTERS|CLUSTER 'name' [[NOT] [I]LIKE 'str'] [LIMIT expr], GRANT, RENAME query, SHOW GRANTS query, SHOW PRIVILEGES, EXISTS, DROP, SYSTEM query, CREATE LIVE VIEW query, CREATE ROW POLICY or ALTER ROW POLICY query, CREATE QUOTA or ALTER QUOTA query, SHOW PROCESSLIST, ALTER QUOTA, CREATE QUOTA, CREATE DATABASE query, SET query, Query, CREATE, WITH, CREATE ROLE or ALTER ROLE query, EXTERNAL DDL FROM, EXCHANGE TABLES, EXISTS or SHOW CREATE query, WATCH query, REPLACE, CREATE ROLE, CREATE SETTINGS PROFILE, SET ROLE or SET DEFAULT ROLE query, CREATE USER or ALTER USER query, EXTERNAL DDL query, SHOW ACCESS query, SHOW CREATE QUOTA query, USE query, ATTACH, DESCRIBE, ALTER TABLE, ShowAccessEntitiesQuery, GRANT or REVOKE query, CREATE TABLE or ATTACH TABLE query","ip":"deepflow-clickhouse","query_time":"0.000000000s","query_uuid":"c691229c-2684-4e28-b03a-9bc9a56a4f71","sql":" FROM flow_log.`l7_flow_log` PREWHERE `time` \u003e= 1666849617 AND `time` \u003c= 1666851417 LIMIT 100"}}
Object

Object
status:500
statusText:"Internal Server Error"
data:Object
message:"{\"OPT_STATUS\":\"FAIL\",\"DESCRIPTION\":\"code: 62, message: Syntax error: failed at position 2 ('FROM'): FROM flow_log.`l7_flow_log` PREWHERE `time` \\u003e= 1666849617 AND `time` \\u003c= 1666851417 LIMIT 100. Expected one of: ALTER query, Query with output, ALTER PROFILE, RENAME DATABASE, SHOW PRIVILEGES query, TRUNCATE, KILL, KILL QUERY query, SELECT query, possibly with UNION, list of union elements, ALTER ROLE, SELECT subquery, DESCRIBE query, SELECT query, subquery, possibly with UNION, SHOW GRANTS, SHOW CREATE, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, WATCH, SHOW PROCESSLIST query, ALTER POLICY, ALTER USER, CREATE VIEW query……

**Comment by liyk1024** [comment]
![image](https://user-images.githubusercontent.com/35055407/198208638-ff392a62-aac8-4f79-a803-307be6588c46.png)
![image](https://user-images.githubusercontent.com/35055407/198208712-daaa2a43-8111-4855-b08e-0cd46a246e8a.png)
![image](https://user-images.githubusercontent.com/35055407/198208735-d6c42c2c-b820-460e-ac78-5c109844e2fc.png)

**Comment by mytting** [comment]
@liyk1024 
Did you upgrade to the latest Grafana dashboard? The latest grafana dashboard requires updating deepflow to v6.1.5. 

Update the documentation:
https://deepflow.yunshan.net/docs/zh/install/upgrade/

**Comment by liyk1024** [comment]
Using v6.1.5 pod will fail to start normally
![image](https://user-images.githubusercontent.com/35055407/198242417-89a57c7e-9b22-4860-9e0c-893d77c76763.png)

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET    /v1/health/               --> github.com/deepflowys/deepflow/server/controller/router.HealthRouter.func1 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :20417
2022-10-27 17:04:27.866 [INFO] [election] election.go:159 election id is node1/192.168.1.4/deepflow-server-0/10.234.169.226
I1027 17:04:27.869012       1 leaderelection.go:248] attempting to acquire leader lease /deepflow-server...
E1027 17:04:27.869656       1 leaderelection.go:330] error retrieving resource lock /deepflow-server: an empty namespace may not be set when a resource name is provided
2022-10-27 17:04:27.870 [ERRO] [election] election.go:129 an empty namespace may not be set when a resource name is provided
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)
[GIN-debug] POST   /v1/query/                --> github.com/deepflowys/deepflow/server/querier/router.executeQuery.func1 (6 handlers)
[GIN-debug] POST   /api/v1/prom/read         --> github.com/deepflowys/deepflow/server/querier/router.promReader.func1 (6 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :20416

**Comment by mytting** [comment]
Has the `helm repo update` been performed?

**Comment by mytting** [comment]
Can you add the wechat at the bottom of the README? Wechat communication efficiency is higher.
