### ISSUE TITLE
PR#1282 follow up

### ISSUE THREAD

**Issue by rvql** [deepflowys/deepflow#1287]
- [ ] 解决libvirt xml extractor可能的死锁问题
- [ ] 重新等待退出

https://github.com/deepflowys/deepflow/pull/1282

**Comment by StrayLittlePunk** [comment]
FIX BY: https://github.com/deepflowys/deepflow/pull/1302

**Comment by StrayLittlePunk** [comment]
查明libvirt xml extractor无死锁问题，是支持npb代码提交删掉停止PcapManager代码，导致无法停止。
