### ISSUE TITLE
How to config grafana datasouce in an existing grafana

### ISSUE THREAD

**Issue by jxwuqingyan** [deepflowys/deepflow#1538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Plugin

### What you expected to happen

我已经有grafana了，不想用自带的grafana，如何添加deeplflow数据源？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mytting** [comment]
That's a good question, and I'll supplement that part of the documentation today

**Comment by mytting** [comment]
PR: https://github.com/deepflowys/docs/pull/170

The download link might not work yet, so you can download the plugin from the link below
```
curl -O https://deepflow-ce.oss-cn-beijing.aliyuncs.com/bin/agent/latest/linux/amd64/deepflow-gui-grafana.tar.gz
```

**Comment by mytting** [comment]
Documentation is online:

https://deepflow.yunshan.net/docs/zh/install/production-deployment/#%E6%8E%A5%E5%85%A5%E5%B7%B2%E6%9C%89%E7%9A%84-grafana
