### ISSUE TITLE
[BUG] Distributed Tracing dashboard no data

### ISSUE THREAD

**Issue by jxwuqingyan** [deepflowys/deepflow#1552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

I have installed deepflow v6.1.6,  and  deploy deepflow-otel-grpc-demo  deepflow-ebpf-spring-demo(all running)，but grafana  dashboards for Distributed Tracing have no data
<img width="1838" alt="image" src="https://user-images.githubusercontent.com/18183044/203493075-b3ff3153-481e-46dd-8d8e-3d13f60f1bec.png">

### DeepFlow version

6.1.6

### Kubernetes CNI

calico

### Operation-System/Kernel version

centos7 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mytting** [comment]
kernel version?

**Comment by mytting** [comment]
The x86 architecture requires a kernel verion greater than 4.14
https://deepflow.yunshan.net/docs/zh/install/overview/#%E8%BF%90%E8%A1%8C%E6%9D%83%E9%99%90%E5%8F%8A%E5%86%85%E6%A0%B8%E8%A6%81%E6%B1%82

**Comment by jxwuqingyan** [comment]
kernel Version is 3.10.0-693.el7.x86_64,it looks like the kernerl problem?

**Comment by mytting** [comment]
Yes, this kernel version is too young to support eBPF.
