### ISSUE TITLE
[FR] FR-004: Hope to support the use of binary agent to collect k8s node data

### ISSUE THREAD

**Issue by DomineCore** [deepflowys/deepflow#1710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In our production cluster, due to high security requirements, we cannot open privileged containers, so we cannot use the daemonset agent normally, because the daemonset agent has applied for sys_admin permission, which will cause the risk of container escape, so we hope to use the binary form The agent collects data to avoid risks and does not affect the normal use of deepflow.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
Solution: An agent in the form of `process` running on each K8s node is responsible for all functions except the list-watch apiserver, and an additional agent running in the form of `K8s deployment` is responsible for the functions of the list-watch apiserver (and inject an ONLY_WATCH_K8S_RESOURCE environment variable).

**Comment by sharang** [comment]
https://github.com/deepflowys/deepflow/pull/2046

will be released (beta) in 6.2.1

cc @mytting @liqian1834
