### ISSUE TITLE
[FR] FR-007: Share the same Agent Config in Different IDCs

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowys/deepflow#1864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In Xiaomi company, our deployment system could not distinguish **deepflow-agent** configs from each idc. In order to make deploy in an easier way, we need all IDCs have a homogeneous config, which needs all config files in different IDC have the same vtap-group-id and the same controller domain name.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
Solution: Currently, deepflow-agent.yaml already supports filling in controller-ips as the domain name. We will improve deepflow-ctl to support filling in an optional group-id parameter when creating agent-group.

```bash
deepflow-ctl agent-group create <group_name> [group_id]
```

**Comment by roryye** [comment]
In version 6.2.0 you can use an optional flag to specify the id, for example `deepflow-ctl agent-group create --id g-1yhIguXABC group_name`
