### ISSUE TITLE
Agent can't capture https request (L7) , when i use get www.sina.cn via  wget or curl

### ISSUE THREAD

**Issue by 23083940** [deepflowys/deepflow#1933]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

Agent can't capture https request (L7) , when i get www.sina.cn via  wget or curl.  
OS is Ubuntu 22.4  
Maybe Wget and curl used gnutls ，that Yunshan Agent can't support ？？ 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mytting** [comment]
The https feature is to hang the hook point on the executable program, which itself takes some time, and for a process like curl that executes immediately, the process may die before the hook point is attached. So one of the things that's done under the hood is to give hook points only to long-running processes.
