### ISSUE TITLE
[BUG] no sub span appear in the dashboard flame chart

### ISSUE THREAD

**Issue by cyxinda** [deepflowys/deepflow#2073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

When I general flame chart,there are no sub span ,as fllow:
there are span level 1
![11111](https://user-images.githubusercontent.com/7237898/210768245-a4402c5d-019c-4fbe-8099-10e5d54d9100.png)
but no sub span level > 1:
![2222](https://user-images.githubusercontent.com/7237898/210768635-0633cdbe-ad07-4b37-9661-729087d5f632.png)
![2](https://user-images.githubusercontent.com/7237898/210769154-9086f19a-53ec-4861-a99d-0f50c322fc2d.png)

### How to reproduce

I track the complete trace link through the requestId. This link has about five layers.
there no sub span except the level 1 layer link.
I think it is a bug.

### DeepFlow version

```bash
[root@server14 ~]# kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
2023/01/05 19:08:16 ENV K8S_NODE_NAME_FOR_DEEPFLOW=server19; K8S_NODE_IP_FOR_DEEPFLOW=192.168.5.19; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-64f6c5884b-n54g9; K8S_POD_IP_FOR_DEEPFLOW=10.244.206.164; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.1.8.2
CommitID: 146338baec86517f58065b6cf00f659a200b207e
RevCount: 7410
Compiler: go version go1.18.9 linux/amd64
CompileTime: 2022-12-23 02:21:41
[root@server14 ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
7462-6c40225afb91c7d3c06bb3a24960f8e9d01c594d
Name: deepflow-agent community edition
Branch: v6.1
CommitId: 6c40225afb91c7d3c06bb3a24960f8e9d01c594d
RevCount: 7462
Compiler: rustc 1.65.0 (897e37553 2022-11-02)
CompileTime: 2023-01-05 10:31:24
[root@server14 ~]# 
```

### DeepFlow agent list

```bash
[root@server14 ~]# deepflow-ctl agent list
NAME        TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP   EXCEPTIONS
server19-V1 K8S_VM     192.168.5.19     b4:96:91:5e:3c:89  NORMAL   default 
server17-V3 K8S_VM     192.168.5.17     b4:96:91:5e:3d:47  NORMAL   default 
```

### Kubernetes CNI

calico  v3.24.5

```bash
[root@server14 ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Operation-System/Kernel version

```bash
[root@server14 ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (Core)"
[root@server14 ~]# uname -r
5.4.221-1.el7.elrepo.x86_64
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mytting** [comment]
One of the nodes failed to run eBPF because sealinux was not closed. After closing sealinux, the agent eBPF ran normally, and the trace data returned to normal. In order to reduce the troubleshooting time of this problem, we will add a sealinux check. When sealinux is not closed print a log.

**Comment by yinjiping** [comment]
@cyxinda 
Use `kubectl logs pod` , find anomalies such as:

```
2023-01-13 01:35:26 [eBPF] WARNING: func ebpf_obj_load() [user/load.c:687] bcc_create_map() failed, name:__active_read_args_map
2023-01-13 01:35:26 [eBPF] WARNING: func ebpf_obj_load() [user/load.c:708] eBPF load programs failed. (errno 13)
```

`errno 13`

Please check SElinux:

```
[root@mars-1 ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```
if found `SELinux status:                 enabled` and `Current mode:                   enforcing` ,please try the following way to solve:
- create file `deepflow-agent.te`
```
module deepflow-agent 1.0;
require {
        type container_runtime_t;
        class bpf { map_create map_read map_write prog_load prog_run };
}
#============= container_runtime_t ==============
allow container_runtime_t self:bpf { map_create map_read map_write prog_load prog_run };
```
- checkmodule -M -m -o deepflow-agent.mod deepflow-agent.te
- semodule_package -o deepflow-agent.pp -m deepflow-agent.mod
- semodule -i deepflow-agent.pp
- restart pod `kubectl get pod deepflow-agent-6f6vd -n deepflow -o yaml  | kubectl replace --force -f -`
- Observe keywords in logs( use `kubectl logs pod`)
```
2023-01-13 01:37:47 [eBPF] INFO Tracer start success, current state: TRACER_RUNNING
```
