### ISSUE TITLE
[BUG] ebpf启动失败

### ISSUE THREAD

**Issue by JimLeeee** [deepflowys/deepflow#2087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

ebpf启动正常

### Operation-System/Kernel version
```
uname -a
Linux jumper-172.21.240.26 4.14.275-207.503.amzn2.x86_64 #1 SMP Wed Apr 13 20:24:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Anything else

journalctl -xeu deepflow-agent|grep -v INFO|grep -v symbols
-- Logs begin at Thu 2022-09-29 22:53:13 UTC, end at Fri 2023-01-06 08:35:50 UTC. --
Jan 06 04:16:40 jumper-172.21.240.26 systemd[1]: Started deepflow-agent.service.
-- Subject: Unit deepflow-agent.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit deepflow-agent.service has finished starting up.
-- 
-- The start-up result is done.
Jan 06 04:16:41 jumper-172.21.240.26 deepflow-agent[30716]: get: 404 - 404
Jan 06 04:16:41 jumper-172.21.240.26 deepflow-agent[30716]: set: 400 - 403
Jan 06 04:16:51 jumper-172.21.240.26 deepflow-agent[30716]: bpf: Failed to load program: Invalid argument
Jan 06 04:16:51 jumper-172.21.240.26 deepflow-agent[30716]: 2023-01-06 4:16:51 [eBPF] WARNING: func load_obj__progs() [user/load.c:426] bcc_prog_load() failed. name: runtime_casgstatus
Jan 06 04:16:51 jumper-172.21.240.26 deepflow-agent[30716]: 2023-01-06 4:16:51 [eBPF] WARNING: func ebpf_obj_load() [user/load.c:734] eBPF load programs failed.
Jan 06 04:16:51 jumper-172.21.240.26 deepflow-agent[30716]: 2023-01-06 4:16:51 [eBPF] WARNING: func tracer_bpf_load() [user/tracer.c:230] bpf load "socket-trace-bpf-linux-common" failed, error:Invalid argument (22)
[root@jumper-172 x86_64]# 
```
![image](https://user-images.githubusercontent.com/46155146/210969844-945b4590-0cd6-4cad-a492-bc284f595d4c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
Calculate LINUX_VERSION_CODE based on kernel version(linux major.minor.patch), use macros KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c)). If the patch number is greater than 255, there will be a deviation. For example, Linux 4.14.275 calculates 265983 with KERNEL_VERSION(4,14,275), and the backderived kernel version is 4.15.19, which is obviously wrong. The solution is to determine the value of patch and set it to 255 if it exceeds 255.

I submitted PR to fix the problem.
https://github.com/deepflowys/deepflow/pull/2150
