### ISSUE TITLE
@jin-xiaofeng [protocol + role] use array instead of map 

### ISSUE THREAD

**Issue by sharang** [deepflowys/deepflow#2098]
@jin-xiaofeng protocol + role 只有4中可能，不要用 Map，用一个数组就行了。 @jin-xiaofeng

_Originally posted by @sharang in https://github.com/deepflowys/deepflow/pull/2094#discussion_r1063995990_

**Comment by jin-xiaofeng** [comment]
fix：  https://github.com/deepflowys/deepflow/pull/2112
