### ISSUE TITLE
No doc,  How to use?

### ISSUE THREAD

**Issue by 23083940** [deepflowys/deepflow#305]
The product presentation was great,  but no "Getting started",  how to use it?

**Comment by mytting** [comment]
@23083940 We are sorting out the usage documents and can sort out the first version this week at the soonest.

**Comment by 23083940** [comment]
thank you

**Comment by sharang** [comment]
@23083940 the Chinese documentation is almost ready, but the English version is still in progress.

https://deepflow.yunshan.net/metaflow-docs/zh/install/overview/
