### ISSUE TITLE
DeepFlow Querier no data returned

### ISSUE THREAD

**Issue by darkfour** [deepflowys/deepflow#405]
按文档https://deepflow.yunshan.net/docs/zh/install/single-k8s/部署，
grafana的三个数据源，其中DeepFlow Querier查不到数据，其余两个数据源有数据，请问是哪里出问题了呢？

**Comment by sharang** [comment]
@darkfour Please submit some troubleshooting information:
- deepflow-agent recent logs, especially warn and err
- deepflow-server recent logs, especially warn and err
- the output of `ip a` on the k8s node of metaflow-agent

**Comment by darkfour** [comment]
> 

deepflow-agent recent logs：
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/31338539/180199504-dda2a848-91a9-4915-a7df-6ae8914bb90c.png">

deepflow-server recent logs：
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/31338539/180200115-68825bc8-6ed6-49a7-8ea2-6f50517906b2.png">


deepflow-server -- elector recent logs：
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/31338539/180199833-1c0391d8-077e-42cf-a594-6dd9cd2b51d3.png">

**Comment by mytting** [comment]
@darkfour 
Was it deepFlow deployed yesterday after 5pm? Is it true that all dashboards in the Deepflow-templates directory have no data and the mysql and Clickhouse dashboards have data? You can try rebooting Grafana to get the latest dashboard and plugin

**Comment by darkfour** [comment]
> 

yes，now，I redeploy it. The mysql and Clickhouse dashboards have data, but all panels have no data

**Comment by darkfour** [comment]
> @darkfour looks like we need more logs
> 
> 1. please upload a log file of `kubectl logs deepflow-server-0 deepflow-server`
> 2. please paste the output of `ip addr show` on the k8s node of deepflow-agent
> 
> thanks.


but I can't log in the k8s node

**Comment by sharang** [comment]
guess you have a special cni. @darkfour can you upload a screenshot like this:

![image](https://user-images.githubusercontent.com/1598518/180369349-ccfeb489-42f4-4814-9ee6-38ba3993f9a4.png)

**Comment by sharang** [comment]
@darkfour 

We are still in the alpha test, some problems may have just been fixed, you can try to reinstall. If you still can't fix it, welcome to join our WeChat group


![image](https://user-images.githubusercontent.com/1598518/180408336-b294523a-8546-44ff-b662-d839a8151486.png)

**Comment by sharang** [comment]
@darkfour Does the problem still exist?
