### ISSUE TITLE
grafana doesn't show the page

### ISSUE THREAD

**Issue by zhangiicc** [deepflowys/deepflow#575]
# Expected Behavior
![image](https://user-images.githubusercontent.com/30918699/183829173-5c0511ba-6045-4e2f-87ca-1467e2c75fee.png)

# Actual Behavior
![image](https://user-images.githubusercontent.com/30918699/183829038-8a6aa950-e80d-4a84-a7ca-e9efd7002cbc.png)

# Steps to Reproduce the Problem

1.# install sealos
curl -o /usr/bin/sealos https://deepflow-ce.oss-cn-beijing.aliyuncs.com/sealos/sealos && \
    chmod +x /usr/bin/sealos
IP_ADDR="192.168.47.24"  
PASSWORD="xxxx"     
sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1 --masters $IP_ADDR -p $PASSWORD
kubectl taint node node-role.kubernetes.io/master- node-role.kubernetes.io/control-plane- --all
sealos run labring/helm:v3.8.2
helm repo add deepflow https://deepflowys.github.io/deepflow
helm install deepflow -n deepflow deepflow/deepflow --create-namespace \
    --set global.allInOneLocalStorage=true
NODE_PORT=$(kubectl get --namespace deepflow -o jsonpath="{.spec.ports[0].nodePort}" services deepflow-grafana)
NODE_IP=$(kubectl get nodes -o jsonpath="{.items[0].status.addresses[0].address}")
echo -e "Grafana URL: http://$NODE_IP:$NODE_PORT  \nGrafana auth: admin:deepflow"

kubectl apply -f https://raw.githubusercontent.com/deepflowys/deepflow-demo/main/DeepFlow-EBPF-Sping-Demo/deepflow-ebpf-spring-demo.yaml

# Additional Info

-  deepflow version:

   **Output of `kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v`:**
  
   **Output of `kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`:**

  ```
 kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v
6228 bc4fbbd25b7527c8df1d1e8eee4d8b31b75f9205 2022-08-09
deepflow-server community edition
go version go1.18.3 linux/amd64

kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
6227-be2d93f5b954db3f8485a953f8201911830fd75e 2022-08-09
deepflow-agent community edition
rustc 1.62.1 (e092d0b6b 2022-07-16)


  ```

- deepflow agent list:

  **Output of `deepflow-ctl agent list`:**
  ```
deepflow-ctl agent list
NAME                                            CTRL_IP                         CTRL_MAC                STATE           EXCEPTIONS
  ```

- Kubernetes CNI:

  ```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "datastore_type": "kubernetes",
      "mtu": 0,
      "nodename_file_optional": false,
      "log_level": "Info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "ipam": { "type": "calico-ipam", "assign_ipv4" : "true", "assign_ipv6" : "false"},
      "container_settings": {
          "allow_ip_forwarding": false
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "k8s_api_root":"https://10.96.0.1:443",
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    },
    {"type": "portmap", "snat": true, "capabilities": {"portMappings": true}}
  ]
}
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  
  **Output of `uname -r`:**
  ```
  awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (Core)"

 uname -r
3.10.0-1127.19.1.el7.x86_64

  ```

**Comment by mytting** [comment]
@zhangiicc Paste the log of DeepFlow-Server DeepFlow-agent.

**Comment by zhangiicc** [comment]
[deepflow-agent.log](https://github.com/deepflowys/deepflow/files/9297510/deepflow-agent.log)
[deepflow-server.log](https://github.com/deepflowys/deepflow/files/9297512/deepflow-server.log)
