### ISSUE TITLE
Documentation Supplement

### ISSUE THREAD

**Issue by Donghui0** [deepflowys/deepflow#64]
Looking forward to this project.
Can you provide more complete best practice documents?  Including: installation setup, configuration instructions, production environment recommendations  etc.

**Comment by sharang** [comment]
We are working hard to clean up the code and the documentation work is going on. Hope to be ready in the next two weeks.

**Comment by sharang** [comment]
@Donghui0 the Chinese documentation is almost ready, but the English version is still in progress.

https://deepflow.yunshan.net/metaflow-docs/zh/install/overview/
