### ISSUE TITLE
An error occurred when the Safire browser opened the dashboard of Grafana

### ISSUE THREAD

**Issue by liqian1834** [deepflowys/deepflow#681]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
![b4426c35fd35657b1baf65828d30831](https://user-images.githubusercontent.com/19233457/186301143-4acccb9d-bdca-4057-9294-f38cf422e727.png)

2.
![02bb5158f8bf702b33b589e107f6498](https://user-images.githubusercontent.com/19233457/186301155-b4d446ef-8c10-462a-bac5-8d8aca9453a8.png)

3.
![978d7e8da4523e92850593c5cb025b7](https://user-images.githubusercontent.com/19233457/186301169-b18011b9-224b-4cbc-86ad-5befc703d75d.png)
![cb5a11afc3b47f890180483b3e70303](https://user-images.githubusercontent.com/19233457/186301181-d77c9d9a-a67b-48a3-98a1-4fed7a528177.png)

# Additional Info

-  deepflow version: 6.1.1

   **Output of `kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v`:**
  
   **Output of `kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`:**

  ```
--
  ```

- deepflow agent list:

  **Output of `deepflow-ctl agent list`:**
  ```
 --
  ```

- Kubernetes CNI:

  ```
 --
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  
  **Output of `uname -r`:**
  ```
  --
  ```

**Comment by twou12031** [comment]
We're happy to report that your issue has been fixed.
If you have any additional questions, please let us know.

**Comment by liqian1834** [comment]
Verify that the problem has been fixed
