### ISSUE TITLE
deepflow clickhouse demand research

### ISSUE THREAD

**Issue by mytting** [deepflowys/deepflow#693]
## Deepflow 6.1.2 version will support the use of external clickhouse, If you have external clickhouse requirements, fill in your external clickhouse related information here

- The cloud vendor of clickhouse you use？
  `Your information`
- Does your hosted clickhouse support the specified number of replicas？
  `Your information`
- Whether each copy of your hosted clickhouse has an independent, fixed IP address？ (IP is not fixed, but the domain name is fixed here as a special note)
  `Your information`
- The version of clickhouse supported by your cloud vendor？
  `Your information`
- Is it possible to provide an external mysql 8.0 containing deepflow and grafana database?
  `Your information`
- Is ClickHouse configured with ZooKeeper?
  `Your information`

**Comment by leon19951027** [comment]
1. self build
2. support
3. yes
4. 21.1.2.15
5.yes

**Comment by withlin** [comment]
> ## Deepflow 6.1.2 version will support the use of external clickhouse, If you have external clickhouse requirements, fill in your external clickhouse related information here
> * The cloud vendor of clickhouse you use？
>   `Your information`
> * Does your hosted clickhouse support the specified number of replicas？
>   `Your information`
> * Whether each copy of your hosted clickhouse has an independent, fixed IP address？ (IP is not fixed, but the domain name is fixed here as a special note)
>   `Your information`
> * The version of clickhouse supported by your cloud vendor？
>   `Your information`
> * Is it possible to provide an external mysql 8.0 containing deepflow and grafana database?
>   `Your information`

1. self build
2. support
3. fixed IP address
4. 20.8/18.16
5. no


<br class="Apple-interchange-newline">
