### ISSUE TITLE
Golang monkey patching library utilized against terms of license

### ISSUE THREAD

**Issue by mattlorimor** [deepflowys/deepflow#874]
The Golang monkey patching library, https://github.com/bouk/monkey, is being utilized directly against [its license](https://github.com/bouk/monkey/blob/master/LICENSE.md):

> Copyright Bouke van der Bijl
> 
> I do not give anyone permissions to use this tool for any purpose. Don't use it.
> 
> I’m not interested in changing this license. Please don’t ask.

It is also archived and not maintained.

**Comment by sharang** [comment]
Thank you very much @mattlorimor , it would be better if there are alternatives you can recommend.

Please @SongZhen0704  follow up on this issue.

```bash
[xiangyang@dev202 deepflow]$ grep -rn bou.ke/monkey server/
server/controller/recorder/updater/subnet_test.go:22:   "bou.ke/monkey"
server/controller/recorder/updater/pod_replica_set_test.go:22:  "bou.ke/monkey"
server/controller/recorder/updater/pod_test.go:22:      "bou.ke/monkey"
server/controller/recorder/updater/routing_table_test.go:22:    "bou.ke/monkey"
server/controller/recorder/updater/cen_test.go:23:      "bou.ke/monkey"
server/controller/recorder/updater/vm_test.go:22:       "bou.ke/monkey"
server/controller/recorder/updater/vinterface_test.go:22:       "bou.ke/monkey"
server/controller/recorder/updater/network_test.go:22:  "bou.ke/monkey"
server/controller/recorder/updater/dhcp_port_test.go:22:        "bou.ke/monkey"
server/controller/recorder/updater/vrouter_test.go:23:  "bou.ke/monkey"
server/go.sum:1:bou.ke/monkey v1.0.2 h1:kWcnsrCNUatbxncxR/ThdYqbytgOIArtYWqcQLQzKLI=
server/go.sum:2:bou.ke/monkey v1.0.2/go.mod h1:OqickVX3tNx6t33n1xvtTtu85YN5s6cKwVug+oHMaIA=
server/go.mod:14:       bou.ke/monkey v1.0.2
```

**Comment by askyrie** [comment]
@ZhengYa-0110 maybe try it  https://github.com/agiledragon/gomonkey

**Comment by xhd2015** [comment]
Hi though this thread was closed, I think there is another better solution, which is xgo ( https://github.com/xhd2015/xgo).

If you like, I will soon issue a PR to replace gomonkey with xgo, that should be simple since I see most monkey patching can be directly replaced by xgo's `mock.Patch` API.

Disclaimer: I'm the creator of xgo who cannot bear gomonkey's bad compatibility.
