### ISSUE TITLE
为什么我按照 “单个集群安装k8s”，都装不好。

### ISSUE THREAD

**Issue by papandadj** [deepflowys/deepflow#959]
# Expected Behavior
安装成功

# Actual Behavior
mysql安装完成后grafana和deepflow server 显示连接不上。进到mysql里面发现根本没执行init脚本。

**Comment by mytting** [comment]
Take a look at mysql's log and descirbe, and is it convenient to add WeChat at the bottom of our readme? We WeChat to communicate
@papandadj

**Comment by mytting** [comment]
We will add troubleshooting documentation later

**Comment by papandadj** [comment]
pv用的 openebs provisioned, 就按照官方资料安装的。通过 `helm install deepflow -n deepflow deepflow/deepflow` 进行安装。地址： https://deepflow.yunshan.net/docs/zh/install/single-k8s/

**这是mysql的日志:**
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/25424898/192750513-942cf50d-4cf6-4ecc-8e10-e464a7459d09.png">

报错是没有报错，但是grafana和server启动不了.
**下面是grafana日志**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25424898/192748361-99b9e065-07a1-4b6d-af72-f6391487ba96.png">
**下面是server日志**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25424898/192750765-f39007d1-ea69-4ad4-9e5d-89c526ac53ad.png">

上回grafana和server报错都是是“is not allowed to connect to this MySQL server”。 
我用helm uninstall 删了deepflow同时也删除deepflow的pvc。重装了下就报上面的错误了。

**这是我的mysql service, 也没问题:**
<img width="837" alt="image" src="https://user-images.githubusercontent.com/25424898/192749191-17958ec5-5e42-41f7-a043-1572d345a076.png">

我进入到mysql pod中看了下用户:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/25424898/192749967-af0d5283-89d9-48fb-b0e7-5415111f07df.png">
没有找见host为%且用户为root的数据。

**Comment by mytting** [comment]
Can you log into mysql using root: DeepFlow?

**Comment by mytting** [comment]
It appears that external access is not authorized

**Comment by papandadj** [comment]
在主机执行：
<img width="631" alt="image" src="https://user-images.githubusercontent.com/25424898/192935480-a094cb6f-c74c-4e96-933f-e56b0ad43c3b.png">


在pod执行：
<img width="626" alt="image" src="https://user-images.githubusercontent.com/25424898/192935713-5e31a945-630e-42b8-b37f-599368531242.png">
都不行， 我没办法在pod里面通过localhost连接。 好像直接使用socket文件连了。


<img width="176" alt="image" src="https://user-images.githubusercontent.com/25424898/192935879-df840ef9-c757-41d3-8dfc-c0cee26f66c5.png">
还有个问题，这个`::`等价于0.0.0.0吗

**Comment by mytting** [comment]
@papandadj 
It seems that mysql fails to initialize successfully, possibly because of poor disk performance. You can delete the data directory of mysql and restart mysql to re-initialize it, and check whether there is any event that fails to restart because of mysql describe. You can add the following to the values-custom file and update it

```yaml
mysql:
  readinessProbe:
    failureThreshold: 20
  livenessProbe:
    failureThreshold: 10
```

In addition, you can use wechat to scan the QR code at the bottom of our ReadMe and join our wechat group. We can communicate in wechat

**Comment by mytting** [comment]
The disk performance problem has been solved
