### ISSUE TITLE
Can flow-log-ttl support hourly dimensionality

### ISSUE THREAD

**Issue by zqzzq** [deepflowys/deepflow#967]
### Feature request

The current unit of flow-log-ttl is days, in my cluster, the data of flow-log in one day reaches 25+Gb, so I want to keep only the last few hours of data, is there a way to achieve this?

**Comment by mytting** [comment]
Shorten flow_log to 30 hours 
Execute the clichouse on all nodes:
```
alter table flow_log.l4_flow_log_local modify ttl time + toIntervalHour(30) 
alter table flow_log.l7_flow_log_local modify ttl time + toIntervalHour(30) 
```
